name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: show pwd
      run: pwd
    - name: list directory
      run: ls .
    - name: Run a multi-line script
      run: |
        cd groupby-python
        python3 app.test.py
