name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check formatted
      run: cd groupby-rust && cargo fmt --all -- --check
    - name: Check 'clippy'
      run: cd groupby-rust && cargo clippy --all --all-targets --all-features
    - name: Build/debug
      run: cd groupby-rust && cargo build --verbose
    - name: Build/release
      run: cd groupby-rust && cargo build --verbose --release
    - name: Run tests/debug
      run: cd groupby-rust && cargo test --all --verbose
    - name: Run tests/release
      run: cd groupby-rust && cargo test --all --verbose --release
